### ISSUE TITLE
datastore on PyPi

### ISSUE THREAD

**Issue by startling** [datastore/datastore#1]
It'd be really cool if datastore were on PyPi -- I'd like to be able to put datastore in a project's `install_requires` and have pip automatically install it.

**Comment by jbenet** [comment]
Added to pypi, as the interface feels somewhat stable, and I've been using it pretty reliably so far. Check it out at: http://pypi.python.org/pypi/datastore

Updated readme and docs install instructions with 9450c9ebfab56ef444f84008d66e19c07df8ecf5.

How to handle the per-datastore modules should be interesting discussion point. I'll open a specific issue for that.
