### ISSUE TITLE
Add travis-ci integration

### ISSUE THREAD

**Issue by jbenet** [datastore/datastore#19]

**Comment by jbenet** [comment]
It's a bit complicated to do CI for all repos, given that some require particular services running. 

I think The Right Way to handle this is to have a docker container for the given service. Then either
1. travis-ci -- when it supports docker.
2. dedicated aws micro instance

**Comment by jbenet** [comment]
See https://github.com/travis-ci/travis-ci/issues/1418

**Comment by willembult** [comment]
Until then, maybe Strider?

http://blog.frozenridge.co/next-generation-continuous-integration-deployment-with-dotclouds-docker-and-strider/

**Comment by willembult** [comment]
Ah, but we'll still have to spin up an instance to run it on; their hosted program is beta and paid.

**Comment by jbenet** [comment]
For now, since this repo doesn't require installing other things (mongo/etc), travis works :) 

https://travis-ci.org/datastore/datastore/builds/13237273
